FILE FREEFORM = 7E374E25-8E01-4FEE-87F2-390C23C606CD {
	SECTION RAW = F11/AcpiTables/0.raw
	SECTION RAW = F11/AcpiTables/1.raw
	SECTION RAW = F11/AcpiTables/2.raw
	SECTION RAW = F11/AcpiTables/3.raw
	SECTION RAW = F11/AcpiTables/4.raw
	SECTION RAW = F11/AcpiTables/5.raw
	SECTION RAW = F11/AcpiTables/6.raw
	SECTION RAW = F11/AcpiTables/7.raw
	SECTION RAW = F11/AcpiTables/8.raw	
	SECTION RAW = F11/AcpiTables/9.raw
#	SECTION RAW = F11/2/0.raw
#	SECTION RAW = F11/2/1.raw
#       SECTION RAW = F11/2/2.raw
#	SECTION RAW = F11/2/3.raw
#	SECTION RAW = F11/2/4.raw
#	SECTION RAW = F11/supermini/5.raw
#	SECTION RAW = F11/855/6.aml
#	SECTION RAW = F11/855/Ice/7.raw
#	SECTION RAW = F11/855/Ice/8.raw
#	SECTION RAW = F11/855/Ice/9.raw


#	SECTION RAW = F11/855/8180/mcfg.bin
#	SECTION RAW = F11/855/old-8180.aml
#	SECTION RAW = F11/855/8180/csrt.bin
#	SECTION RAW = F11/855/8180/bgrt.bin   
#	SECTION RAW = F11/855/8180/fpdt.bin  
#	SECTION RAW = F11/855/8180/pptt.bin     
#	SECTION RAW = F11/855/8180/tpm2.bin
#	SECTION RAW = F11/855/8180/facp.bin  
#	SECTION RAW = F11/855/8180/mcfg.bin   
#	SECTION UI = "AcpiTables"
  }
